shutdown_costmaps: false
controller_frequency: 5.0
controller_patience: 3.0
planner_frequency: 3.0
planner_patience: 3.0
oscillation_timeout: 10.0
oscillation_distance: 0.5
base_local_planner: "dwa_local_planner/DWAPlannerROS"
base_global_planner: "global_planner/GlobalPlanner"
clearing_rotation_allowed: true
recovery_behavior_enabled: true
recovery_behaviors:
  - name: 'super_conservative_reset1'
    type: 'clear_costmap_recovery2/ClearCostmapRecovery'
  - name: 'conservative_reset1'
    type: 'clear_costmap_recovery2/ClearCostmapRecovery'
  - name: 'aggressive_reset1'
    type: 'clear_costmap_recovery2/ClearCostmapRecovery'
  - name: 'clearing_rotation1'
    type: 'rotate_recovery/RotateRecovery'
  - name: 'super_conservative_reset2'
    type: 'clear_costmap_recovery2/ClearCostmapRecovery'
  - name: 'conservative_reset2'
    type: 'clear_costmap_recovery2/ClearCostmapRecovery'
  - name: 'aggressive_reset2'
    type: 'clear_costmap_recovery2/ClearCostmapRecovery'
  - name: 'clearing_rotation2'
    type: 'rotate_recovery/RotateRecovery'
super_conservative_reset1:
  reset_distance: 0.5
conservative_reset1:
  reset_distance: 0.0
aggressive_reset1:
  reset_distance: 0.0
super_conservative_reset2:
  reset_distance: 0.0
conservative_reset2:
  reset_distance: 0.0
aggressive_reset2:
  reset_distance: 0.0
